module.exports = {
  ERR_SBEE_0001: "Failed to connect to db",
  ERR_SBEE_0002: "Error in fetching ticket from Tableau",
  ERR_SBEE_0003: "Email already exists. Please try login 😐  ",
  ERR_SBEE_0004: "Phone number is already in use 😐",
  ERR_SBEE_0005: "Admin account does not exist 😰",
  ERR_SBEE_0006: "Merchant account not found 😰",
  ERR_SBEE_0007: "Invalid Password 💢",
  ERR_SBEE_0008: "Oops! ID not found 😰",
  ERR_SBEE_0009: "Some error occurred ! Please try again later 😖",
  ERR_SBEE_0010: "Oops! No items to show 😰 ",
  ERR_SBEE_0011: "Transaction failed! invalid hash values 🤯",
  ERR_SBEE_0012: "Old password mismatch.Please try again",
  ERR_SBEE_0013: "Your subscription is expired .Please contact the admin 💢",
  ERR_SBEE_0014: "Error occured.Please try again 😷",
  ERR_SBEE_0015: "Transaction failed! invalid signature values 🤯",
  ERR_SBEE_0016: "Webhooks not authenticated. Payment failure 🤯",
  ERR_SBEE_0017: "Requested amount cannot be higher than the paid amount",
  ERR_SBEE_0018: "Refund request not found. Initiate refund to view status ",
  ERR_SBEE_0019: "Payment gateway server not reached.Please try again 😖",
  ERR_SBEE_0020: "Transaction verification mismatch. Please try again 🤯	",
  ERR_SBEE_0021: "Order and paid amount does not match. Please contact the store 🤯	",
  ERR_SBEE_0022: "Please enter a valid transaction ID 😡 ",
  ERR_SBEE_0023: "No items to show 😰 ",
  ERR_SBEE_0024: "No transaction settlements for the day",
  ERR_SBEE_0025: "Account already logged-in on another device 😖",
  ERR_SBEE_0026: "Stock feature not enabled for the product ",
  ERR_SBEE_0027: "Invalid/expired billing key",
  ERR_SBEE_0028: "No billing key provided",
  ERR_SBEE_0029: "Your app trial version has expired. Kindly subscribe to unlock all the features",
  ERR_SBEE_0030: "Device ID not detected",
  ERR_SBEE_0031: "Cannot create duplicate for same store and terminal",
  ERR_SBEE_0032: "Action can be done only with the paid account",
  ERR_SBEE_0033: "Account with specified role doesn't exist",
  ERR_SBEE_0034: "New password cannot be old password 💢",
  ERR_SBEE_0035: "Your terminal subscription is expired .Please contact the admin 💢",
  ERR_SBEE_0036: "Terminal account not found 😰",
  ERR_SBEE_0037: "Terminal subscription payment not completed ",
  ERR_SBEE_0038: "Error in sending mail request.Please try again later ",
  ERR_SBEE_0039: "Error. Your account does not have the access",
  ERR_SBEE_0040: "Store and terminal ID mandatory",
  ERR_SBEE_0041: "Store staff role already assingned for this terminal",
  ERR_SBEE_0042: "Staff and terminal number mandatory",
  ERR_SBEE_0043: "Store ID mandatory",
  ERR_SBEE_0044: "Password mismatch 💢",
  ERR_SBEE_0045: "Terminal access already given to another staff. Do you wish to switch access? ",
  ERR_SBEE_0046: "Terminal access not linked with any staff yet. ",
  ERR_SBEE_0047: "Master terminal access cannot be linked with other staff. ",
  ERR_SBEE_0048: "Staff contact number didn't match. Please try again ",
  ERR_SBEE_0049: "Staff account does not exist",
  ERR_SBEE_0050: "Staff already linked with other terminal. Do you wish to assign additional terminal to the same staff?",
  ERR_SBEE_0051: "Staff already linked with terminal. Kindly remove terminal access before deleting staff account.",
  ERR_SBEE_0052: "Last order transaction cancelled.",
  ERR_SBEE_0053: "No files uploaded",
  ERR_SBEE_0054: "Remove your product and addon mapping before deleting addon.",
  ERR_SBEE_0055: "Billing key changed recently. Kindly contact your master account",
  ERR_SBEE_0056: "No estimator found for the order Id",
  ERR_SBEE_0057: "Multiple unpaid terminals cannot co-exist inside the store ",
  ERR_SBEE_0058: "Name already exists. Please try a different name",
  ERR_SBEE_0991: "Merchant role mandatory 😷 ",
  ERR_SBEE_0992: "role does not exist 😷 ",
  ERR_SBEE_0993: "Not authorized. Require master access 😷 ",
  ERR_SBEE_0994: "Not authorized.Your role does not have the access 😷",
  ERR_SBEE_0997: "Forbidden access 😷 ",
  ERR_SBEE_0998: "UnAuthorized 🤨",
  ERR_SBEE_0999: "No token provided! 🤨",





};
